### PR TITLE
unlimit and change promotion order

### PR DESCRIPTION
**Pull request by 12Metatron**
unlimit flute charmer and change promotion order

### CODE REVIEW

**Comment by MrTurtleJr** [comment]
Line 13 currently reads "The Flute Charmer becomes a flute player if The Flute Charmer becomes a flute player if no other flute team roles remain." as far as I can see - that should be changed.

**Comment by MrTurtleJr** [comment]
Considering that both the Flute Player and the Flute Apprentice capitalize every instance of 'Flute Player' (instead of flute player) and 'Flute team' (instead of flute team), perhaps this could be done with the Flute Charmer as well in the name of standardized capitalization/orthography?

**Comment by McTsts** [comment]
> Considering that both the Flute Player and the Flute Apprentice capitalize every instance of 'Flute Player' (instead of flute player) and 'Flute team' (instead of flute team), perhaps this could be done with the Flute Charmer as well in the name of standardized capitalization/orthography?

we usually aim to only capitalize the current role / game element. I dont think capitalizing solo primary in solo secondary is something we do for other teams (or do we? should we?)

**Comment by MrTurtleJr** [comment]
> > Considering that both the Flute Player and the Flute Apprentice capitalize every instance of 'Flute Player' (instead of flute player) and 'Flute team' (instead of flute team), perhaps this could be done with the Flute Charmer as well in the name of standardized capitalization/orthography?
> 
> we usually aim to only capitalize the current role / game element. I dont think capitalizing solo primary in solo secondary is something we do for other teams (or do we? should we?)

Oh okay. That's fair, I saw that with Hell team, where Demon does not capitalize devil. However, I was going off of FPA description, which does do this. In any case, then that would have to change. 
However, what about Flute team? From what I can tell, it is capitalized in the FP and FPA descriptions. For Devil and Demon it seems to be roughly 50/50. Are alignments capitalized?

**Comment by McTsts** [comment]
> > > Considering that both the Flute Player and the Flute Apprentice capitalize every instance of 'Flute Player' (instead of flute player) and 'Flute team' (instead of flute team), perhaps this could be done with the Flute Charmer as well in the name of standardized capitalization/orthography?
> > 
> > 
> > we usually aim to only capitalize the current role / game element. I dont think capitalizing solo primary in solo secondary is something we do for other teams (or do we? should we?)
> 
> Oh okay. That's fair, I saw that with Hell team, where Demon does not capitalize devil. However, I was going off of FPA description, which does do this. In any case, then that would have to change. However, what about Flute team? From what I can tell, it is capitalized in the FP and FPA descriptions. For Devil and Demon it seems to be roughly 50/50. Are alignments capitalized?

The only specific captialization rule we formally recognize is doing it for the current role's name. We could do it for solo alignments (from their solo roles) and solo primaries (from their secondaries) as well which would make sense, but this is currently not defined. (Should we change this?)

Right now we just have:

"In a role's description the name of the role itself is capitalized, but other role names are not." defined over [here](https://github.com/WerewolvesRevamped/Werewolves-Roles?tab=readme-ov-file#public-information)

**Review by McTsts — APPROVED** [review]

**Pull request merged**
